### PR TITLE
feat: instantiable cannelloni_ports

### PR DESCRIPTION
**Pull request by federico-carbone**
Removed all global variables and defines and put it into an handle structure, in order to allow more than a connection.

### CODE REVIEW

**Comment by mguentner** [comment]
Nice, I like it! Do you have further changes to add as the PR is marked as draft?

We can merge it like this as the original code is not functional anyway.

**Comment by federico-carbone** [comment]
Hi sorry for the late reply.
Yes you can merge, it's all done!
Thank you

**Comment by trnila** [comment]
Works great.
Could we also pass `cannelloni_handle_t*` to both callbacks `can_rx_fn` and `can_tx_fn` so its possible to call `get_can_rx_frame` on a right handle? And also add some `void* user_data` to `cannelloni_handle_t` struct so we can pass platform specific data like CAN peripheral register address or custom struct for a platform driver?

**Comment by federico-carbone** [comment]
Sure I'll implement it asap!

**Comment by federico-carbone** [comment]
> Works great.
> Could we also pass `cannelloni_handle_t*` to both callbacks `can_rx_fn` and `can_tx_fn` so its possible to call `get_can_rx_frame` on a right handle? And also add some `void* user_data` to `cannelloni_handle_t` struct so we can pass platform specific data like CAN peripheral register address or custom struct for a platform driver?

Sure I'll implement it asap!

**Comment by mguentner** [comment]
Sorry this hasn't been merged yet. I will do it after your adjustments as suggested by @trnila!

**Comment by federico-carbone** [comment]
And here we go, ready to be merged as far as I'm concerned!

**Comment by mguentner** [comment]
LGTM :+1:

**Pull request merged**
